language: java
#language
script: mvn package

env:
  global:
    # sets the HEROKU_API_KEY for Heroku deploys
    - secure: "JrPeMkwE/45KjoIi4GYHxFJhnhaYeKFFyJJS0ujK+ccpjDdN4Im2cL2qpGhQT/xcIRyFg+Hz537BkJSPrl1lyRZ9Q7gbNUlRiO3JTgVHw+hBMGtd5fzgtAqiQOgHocEaffA4AO/KwTGJJsYBs7ssZ6z2tyg++UxD6rOOFnmuM5w="

after_success:
  - ./deploy.sh "$HEROKU_API_KEY"

deploy:
  provider: releases
  user: "ngundu"
  password: "india@003"
  file: "travis-heroku-java-example.war"
  skip_cleanup: true
  on:
    tags: true  